### ISSUE TITLE
Buzz location

### ISSUE THREAD

**Issue by lizliz** [lizliz/teaspoon#21]
Need to think about where buzz is placed. There are ideas in there that are useful for general TDA stuff, namely setting up a zigzag diagram from a series of point clouds.  That part should definitely be in the TDA module.  But, the application to time series should probably be elsewhere? 

Also, while we're messing with any of this, we should be thinking about how to set up whatever part is left in the general TDA module to accept graph inputs as well as point clouds.

**Comment by sarahtymochko** [comment]
Looking back at the buzz code, I think it is all completely general to point clouds. The example in the documentation is a time series one because those were the examples I had coded up. So we could do one of two things:

1. Rewording documentation/change heading of page to emphasize the method comes from the BuZZ paper but is more broadly applicable to anything fitting the pipeline: point clouds -> rips complexes -> zigzag).
2. Move it somewhere else entirely. I think I only put it in TDA because I didn't know where else it would fit and I was trying to make sure it got merged into teaspoon before I switched jobs for the summer :)
